// <auto-generated />
using System;
using GameStatistics.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameStatistics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240113134316_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameStatistics.Models.GameData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AverageBetAmount")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("PopularityScore")
                        .HasColumnType("real");

                    b.Property<int>("TotalBets")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GamesData", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e33746ed-0790-48ae-9e42-a970fa22c9da"),
                            AverageBetAmount = 10.5f,
                            Category = "Casinos",
                            GameName = "Poker",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9173),
                            PopularityScore = 8.2f,
                            TotalBets = 1000,
                            TotalWins = 500
                        },
                        new
                        {
                            Id = new Guid("4f631c44-5485-4ef6-ac2f-ca78cd5f27f0"),
                            AverageBetAmount = 15.2f,
                            Category = "Casinos",
                            GameName = "Blackjack",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9204),
                            PopularityScore = 7.6f,
                            TotalBets = 1500,
                            TotalWins = 800
                        },
                        new
                        {
                            Id = new Guid("5ab7593a-1a27-4989-8f04-d215004765ea"),
                            AverageBetAmount = 2.5f,
                            Category = "Recreational machines",
                            GameName = "Slot Machines",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9215),
                            PopularityScore = 9.3f,
                            TotalBets = 5000,
                            TotalWins = 2000
                        },
                        new
                        {
                            Id = new Guid("f5a2ece4-7623-43ac-a122-ebc91089d2d4"),
                            AverageBetAmount = 20f,
                            Category = "Casinos",
                            GameName = "Roulette",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9224),
                            PopularityScore = 6.9f,
                            TotalBets = 2000,
                            TotalWins = 1000
                        },
                        new
                        {
                            Id = new Guid("c3e8c6de-2df7-4b76-9d41-7ab08708a382"),
                            AverageBetAmount = 12.8f,
                            Category = "Casinos",
                            GameName = "Craps",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9234),
                            PopularityScore = 5.4f,
                            TotalBets = 800,
                            TotalWins = 300
                        },
                        new
                        {
                            Id = new Guid("ae9c1c55-9aaf-46da-87b2-6aed9ae7d6bb"),
                            AverageBetAmount = 5.7f,
                            Category = "Recreational machines",
                            GameName = "Bingo",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9245),
                            PopularityScore = 7.8f,
                            TotalBets = 300,
                            TotalWins = 150
                        },
                        new
                        {
                            Id = new Guid("4a47b239-3a41-43c3-8ec1-c3666f744e01"),
                            AverageBetAmount = 6.2f,
                            Category = "Recreational machines",
                            GameName = "Keno",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9255),
                            PopularityScore = 6.1f,
                            TotalBets = 400,
                            TotalWins = 200
                        },
                        new
                        {
                            Id = new Guid("111aebe7-1d35-4df9-be22-c94716bf65bd"),
                            AverageBetAmount = 50f,
                            Category = "Sports",
                            GameName = "Sports Betting",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9265),
                            PopularityScore = 9.7f,
                            TotalBets = 5000,
                            TotalWins = 2500
                        },
                        new
                        {
                            Id = new Guid("a26c8941-76dd-4b04-8f8a-c538c49face2"),
                            AverageBetAmount = 25f,
                            Category = "Sports",
                            GameName = "Horse Racing",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9274),
                            PopularityScore = 8.4f,
                            TotalBets = 3000,
                            TotalWins = 1200
                        },
                        new
                        {
                            Id = new Guid("c34bca87-b6bd-4db4-aab6-867b602fda36"),
                            AverageBetAmount = 35f,
                            Category = "Sports",
                            GameName = "Soccer Betting",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9284),
                            PopularityScore = 7.2f,
                            TotalBets = 2000,
                            TotalWins = 900
                        },
                        new
                        {
                            Id = new Guid("11debc72-3852-4c3a-b150-497b730afbf7"),
                            AverageBetAmount = 42f,
                            Category = "Sports",
                            GameName = "Basketball Betting",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9293),
                            PopularityScore = 6.8f,
                            TotalBets = 1800,
                            TotalWins = 800
                        },
                        new
                        {
                            Id = new Guid("39290877-93d0-4845-a2ad-522ebf690448"),
                            AverageBetAmount = 48f,
                            Category = "Sports",
                            GameName = "Baseball Betting",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9302),
                            PopularityScore = 6.5f,
                            TotalBets = 1500,
                            TotalWins = 700
                        },
                        new
                        {
                            Id = new Guid("8fd48a61-5e1a-4740-9681-35802e725a79"),
                            AverageBetAmount = 55f,
                            Category = "Sports",
                            GameName = "Cricket Betting",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9312),
                            PopularityScore = 6.2f,
                            TotalBets = 1200,
                            TotalWins = 600
                        },
                        new
                        {
                            Id = new Guid("41bcf3a1-159e-4f3d-b95d-a4e796871036"),
                            AverageBetAmount = 60f,
                            Category = "Sports",
                            GameName = "Tennis Betting",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9321),
                            PopularityScore = 6f,
                            TotalBets = 1000,
                            TotalWins = 500
                        },
                        new
                        {
                            Id = new Guid("c884c080-4673-40f7-a540-be097d404a5a"),
                            AverageBetAmount = 70f,
                            Category = "Sports",
                            GameName = "Golf Betting",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9330),
                            PopularityScore = 5.7f,
                            TotalBets = 800,
                            TotalWins = 400
                        },
                        new
                        {
                            Id = new Guid("9234da64-2a9f-4885-8fe7-f5f636fe0bb5"),
                            AverageBetAmount = 80f,
                            Category = "Sports",
                            GameName = "Boxing Betting",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9339),
                            PopularityScore = 5.4f,
                            TotalBets = 600,
                            TotalWins = 300
                        },
                        new
                        {
                            Id = new Guid("1a37fa34-3940-4628-b1ed-dd7ab1ba1b7f"),
                            AverageBetAmount = 100f,
                            Category = "Sports",
                            GameName = "MMA Betting",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9348),
                            PopularityScore = 5.1f,
                            TotalBets = 400,
                            TotalWins = 200
                        },
                        new
                        {
                            Id = new Guid("1c036f58-e259-45d7-a88c-0082f542bb97"),
                            AverageBetAmount = 200f,
                            Category = "Sports",
                            GameName = "Cycling Betting",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9359),
                            PopularityScore = 4.8f,
                            TotalBets = 200,
                            TotalWins = 100
                        },
                        new
                        {
                            Id = new Guid("cd950473-3c70-4c47-9787-2ca888fb9ddd"),
                            AverageBetAmount = 10f,
                            Category = "Recreational machines",
                            GameName = "Fishing Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9368),
                            PopularityScore = 7.5f,
                            TotalBets = 100,
                            TotalWins = 50
                        },
                        new
                        {
                            Id = new Guid("d7c9e809-4615-4111-9593-04d6c837bdf4"),
                            AverageBetAmount = 5f,
                            Category = "Recreational machines",
                            GameName = "Bowling Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9377),
                            PopularityScore = 6.7f,
                            TotalBets = 50,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("60321e6e-1513-4304-8ee6-fe63ef782ca1"),
                            AverageBetAmount = 8f,
                            Category = "Recreational machines",
                            GameName = "Darts Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9385),
                            PopularityScore = 6f,
                            TotalBets = 80,
                            TotalWins = 30
                        },
                        new
                        {
                            Id = new Guid("87fd4045-8506-4f9a-9caf-7d389cb7f6ae"),
                            AverageBetAmount = 12f,
                            Category = "Recreational machines",
                            GameName = "Guitar Hero Arcade",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9394),
                            PopularityScore = 8.7f,
                            TotalBets = 120,
                            TotalWins = 60
                        },
                        new
                        {
                            Id = new Guid("8d6d1429-6fc2-441a-8e1f-977df16efeca"),
                            AverageBetAmount = 9f,
                            Category = "Recreational machines",
                            GameName = "Air Hockey",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9403),
                            PopularityScore = 7.9f,
                            TotalBets = 90,
                            TotalWins = 40
                        },
                        new
                        {
                            Id = new Guid("6b1e550b-be64-474b-a05f-4eed694472f5"),
                            AverageBetAmount = 7f,
                            Category = "Recreational machines",
                            GameName = "Foosball",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9412),
                            PopularityScore = 6.3f,
                            TotalBets = 70,
                            TotalWins = 25
                        },
                        new
                        {
                            Id = new Guid("a6ae2f12-ec04-4f83-8e68-74c8953c735a"),
                            AverageBetAmount = 6f,
                            Category = "Recreational machines",
                            GameName = "Skiing Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9421),
                            PopularityScore = 5.6f,
                            TotalBets = 60,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("afe04999-dcf2-4d9e-bd0f-f3e2a35de771"),
                            AverageBetAmount = 10f,
                            Category = "Recreational machines",
                            GameName = "Basketball Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9445),
                            PopularityScore = 7.2f,
                            TotalBets = 100,
                            TotalWins = 40
                        },
                        new
                        {
                            Id = new Guid("9608e874-0739-4b9f-959c-e5d42dc541f5"),
                            AverageBetAmount = 15f,
                            Category = "Recreational machines",
                            GameName = "Football Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9477),
                            PopularityScore = 8.4f,
                            TotalBets = 150,
                            TotalWins = 60
                        },
                        new
                        {
                            Id = new Guid("e7c1bec8-2ab8-4fd1-9105-4852d1556dc6"),
                            AverageBetAmount = 8f,
                            Category = "Recreational machines",
                            GameName = "Golf Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9488),
                            PopularityScore = 6.9f,
                            TotalBets = 80,
                            TotalWins = 30
                        },
                        new
                        {
                            Id = new Guid("13e93757-59ae-4c80-8ae9-8a8e2811a01f"),
                            AverageBetAmount = 7f,
                            Category = "Recreational machines",
                            GameName = "Tennis Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9498),
                            PopularityScore = 6.1f,
                            TotalBets = 70,
                            TotalWins = 25
                        },
                        new
                        {
                            Id = new Guid("925c8d5c-b4f3-48ba-8b24-583c353839dd"),
                            AverageBetAmount = 5f,
                            Category = "Recreational machines",
                            GameName = "Volleyball Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9508),
                            PopularityScore = 5.3f,
                            TotalBets = 50,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("8233527f-fd4b-42f7-bec1-d4262c142de6"),
                            AverageBetAmount = 4f,
                            Category = "Recreational machines",
                            GameName = "Cricket Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9518),
                            PopularityScore = 4.6f,
                            TotalBets = 40,
                            TotalWins = 15
                        },
                        new
                        {
                            Id = new Guid("a673642f-5143-452b-b650-22d90bf6be4d"),
                            AverageBetAmount = 3f,
                            Category = "Recreational machines",
                            GameName = "Hockey Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9530),
                            PopularityScore = 3.9f,
                            TotalBets = 30,
                            TotalWins = 10
                        },
                        new
                        {
                            Id = new Guid("862e3cc9-8475-45a0-8a1d-6457c988f981"),
                            AverageBetAmount = 9f,
                            Category = "Recreational machines",
                            GameName = "Racing Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9540),
                            PopularityScore = 7.5f,
                            TotalBets = 90,
                            TotalWins = 40
                        },
                        new
                        {
                            Id = new Guid("220d1caa-71e3-474c-a939-31877d246de3"),
                            AverageBetAmount = 6f,
                            Category = "Recreational machines",
                            GameName = "Boxing Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9551),
                            PopularityScore = 6.2f,
                            TotalBets = 60,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("d57982f4-36fb-44f5-b0f6-c3dfc026ed5e"),
                            AverageBetAmount = 4f,
                            Category = "Recreational machines",
                            GameName = "Wrestling Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9561),
                            PopularityScore = 5.1f,
                            TotalBets = 40,
                            TotalWins = 15
                        },
                        new
                        {
                            Id = new Guid("a25a2a54-8ddf-44ab-9985-0e085a6ffde3"),
                            AverageBetAmount = 8f,
                            Category = "Recreational machines",
                            GameName = "Soccer Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9571),
                            PopularityScore = 6.7f,
                            TotalBets = 80,
                            TotalWins = 30
                        },
                        new
                        {
                            Id = new Guid("5856b3c4-1a41-40b8-986f-722f41488b76"),
                            AverageBetAmount = 7f,
                            Category = "Recreational machines",
                            GameName = "Baseball Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9581),
                            PopularityScore = 6f,
                            TotalBets = 70,
                            TotalWins = 25
                        },
                        new
                        {
                            Id = new Guid("b47542d0-44fb-4346-8677-a15ebdf3ce34"),
                            AverageBetAmount = 5f,
                            Category = "Recreational machines",
                            GameName = "Basketball Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9592),
                            PopularityScore = 5.4f,
                            TotalBets = 50,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("1af990a3-fe48-45de-b15e-33f8dbf63427"),
                            AverageBetAmount = 3f,
                            Category = "Recreational machines",
                            GameName = "Volleyball Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9601),
                            PopularityScore = 4.8f,
                            TotalBets = 30,
                            TotalWins = 10
                        },
                        new
                        {
                            Id = new Guid("746de52f-dc12-4a0f-9450-de9390768d97"),
                            AverageBetAmount = 4f,
                            Category = "Recreational machines",
                            GameName = "Tennis Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9611),
                            PopularityScore = 4.2f,
                            TotalBets = 40,
                            TotalWins = 15
                        },
                        new
                        {
                            Id = new Guid("9270e2e0-497a-46f4-aacb-09ef98d24f80"),
                            AverageBetAmount = 6f,
                            Category = "Recreational machines",
                            GameName = "Golf Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9621),
                            PopularityScore = 5.6f,
                            TotalBets = 60,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("10b219c8-b80a-4ad2-989a-953f52a847a7"),
                            AverageBetAmount = 5f,
                            Category = "Recreational machines",
                            GameName = "Cricket Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9630),
                            PopularityScore = 5f,
                            TotalBets = 50,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("3f181897-9608-43c7-abae-1b1b19e6d02e"),
                            AverageBetAmount = 3f,
                            Category = "Recreational machines",
                            GameName = "Hockey Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9640),
                            PopularityScore = 4.4f,
                            TotalBets = 30,
                            TotalWins = 10
                        },
                        new
                        {
                            Id = new Guid("58e26e52-7efb-4215-9d8c-35f066370210"),
                            AverageBetAmount = 4f,
                            Category = "Recreational machines",
                            GameName = "Racing Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9650),
                            PopularityScore = 4.9f,
                            TotalBets = 40,
                            TotalWins = 15
                        },
                        new
                        {
                            Id = new Guid("a3829083-5598-41b2-8ea2-a0a333901c1e"),
                            AverageBetAmount = 6f,
                            Category = "Recreational machines",
                            GameName = "Boxing Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9660),
                            PopularityScore = 5.5f,
                            TotalBets = 60,
                            TotalWins = 20
                        },
                        new
                        {
                            Id = new Guid("fe93ed6e-f17c-487e-bc0e-b3f5dfb8f450"),
                            AverageBetAmount = 7f,
                            Category = "Recreational machines",
                            GameName = "Wrestling Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9670),
                            PopularityScore = 6f,
                            TotalBets = 70,
                            TotalWins = 25
                        },
                        new
                        {
                            Id = new Guid("75878170-cccc-4023-bce6-31471f735cf6"),
                            AverageBetAmount = 8f,
                            Category = "Recreational machines",
                            GameName = "Soccer Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9680),
                            PopularityScore = 6.5f,
                            TotalBets = 80,
                            TotalWins = 30
                        },
                        new
                        {
                            Id = new Guid("0942b1e8-1c73-4ef4-8bb5-63af0c4f2c0a"),
                            AverageBetAmount = 9f,
                            Category = "Recreational machines",
                            GameName = "Baseball Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9689),
                            PopularityScore = 7f,
                            TotalBets = 90,
                            TotalWins = 40
                        },
                        new
                        {
                            Id = new Guid("37747df6-62de-42bf-a2e2-ded6bc5b70b5"),
                            AverageBetAmount = 10f,
                            Category = "Recreational machines",
                            GameName = "Basketball Game",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9699),
                            PopularityScore = 7.5f,
                            TotalBets = 100,
                            TotalWins = 40
                        },
                        new
                        {
                            Id = new Guid("121c32c3-3084-4e37-8739-50200b113387"),
                            AverageBetAmount = 10.5f,
                            Category = "Card Game",
                            GameName = "Poker",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9709),
                            PopularityScore = 8.7f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("b493fd80-c0a4-48a5-803a-f9787825302a"),
                            AverageBetAmount = 15.2f,
                            Category = "Card Game",
                            GameName = "Blackjack",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9719),
                            PopularityScore = 9.2f,
                            TotalBets = 15000,
                            TotalWins = 7500
                        },
                        new
                        {
                            Id = new Guid("10e2acec-98e9-470a-adcf-2c2a1beccd6d"),
                            AverageBetAmount = 25f,
                            Category = "Table Game",
                            GameName = "Roulette",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9729),
                            PopularityScore = 7.9f,
                            TotalBets = 20000,
                            TotalWins = 10000
                        },
                        new
                        {
                            Id = new Guid("0bcaabf8-9bd9-49c9-8e9a-8b682ce04492"),
                            AverageBetAmount = 5f,
                            Category = "Recreational Machine",
                            GameName = "Slot Machine",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9762),
                            PopularityScore = 9.8f,
                            TotalBets = 50000,
                            TotalWins = 25000
                        },
                        new
                        {
                            Id = new Guid("a681b18a-bedd-4a93-9360-eeb7a1ad9763"),
                            AverageBetAmount = 20f,
                            Category = "Card Game",
                            GameName = "Baccarat",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9772),
                            PopularityScore = 6.5f,
                            TotalBets = 8000,
                            TotalWins = 4000
                        },
                        new
                        {
                            Id = new Guid("3164b1a8-5c4d-497c-9df9-5a6dd228bae7"),
                            AverageBetAmount = 18.2f,
                            Category = "Table Game",
                            GameName = "Craps",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9783),
                            PopularityScore = 7.1f,
                            TotalBets = 12000,
                            TotalWins = 6000
                        },
                        new
                        {
                            Id = new Guid("ad104886-ee40-4a14-b6d1-234f05f3e169"),
                            AverageBetAmount = 2.5f,
                            Category = "Recreational Game",
                            GameName = "Keno",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9793),
                            PopularityScore = 5.3f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        },
                        new
                        {
                            Id = new Guid("352b6067-f3ba-43eb-bf74-44e53a8e57c1"),
                            AverageBetAmount = 10f,
                            Category = "Dice Game",
                            GameName = "Sic Bo",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9803),
                            PopularityScore = 4.6f,
                            TotalBets = 6000,
                            TotalWins = 3000
                        },
                        new
                        {
                            Id = new Guid("8a2fb661-4473-4fc8-9e10-4df1c6ffe881"),
                            AverageBetAmount = 12.5f,
                            Category = "Card Game",
                            GameName = "Pai Gow Poker",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9813),
                            PopularityScore = 6.9f,
                            TotalBets = 7000,
                            TotalWins = 3500
                        },
                        new
                        {
                            Id = new Guid("88461d8e-89c6-45ac-a6da-0849fff451b8"),
                            AverageBetAmount = 10f,
                            Category = "Recreational Machine",
                            GameName = "Wheel of Fortune",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9823),
                            PopularityScore = 8.2f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("d418071b-eb4c-42bf-9f8f-f890d6b01f25"),
                            AverageBetAmount = 15.3f,
                            Category = "Card Game",
                            GameName = "Texas Hold'em",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9834),
                            PopularityScore = 9.5f,
                            TotalBets = 18000,
                            TotalWins = 9000
                        },
                        new
                        {
                            Id = new Guid("7f254273-f828-4e41-a4a6-4726c04ff163"),
                            AverageBetAmount = 10f,
                            Category = "Card Game",
                            GameName = "Three Card Poker",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9844),
                            PopularityScore = 8.4f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("62cb172c-ed06-4d82-9723-4463e11ff3b6"),
                            AverageBetAmount = 5f,
                            Category = "Recreational Game",
                            GameName = "Bingo",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9853),
                            PopularityScore = 7.6f,
                            TotalBets = 4000,
                            TotalWins = 2000
                        },
                        new
                        {
                            Id = new Guid("17b0467d-fbba-41af-be2c-36d9ce1186e9"),
                            AverageBetAmount = 8f,
                            Category = "Card Game",
                            GameName = "Red Dog",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9863),
                            PopularityScore = 5.9f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        },
                        new
                        {
                            Id = new Guid("efcc6d32-ca3f-4250-bca9-53cee747f893"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Pachinko",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9873),
                            PopularityScore = 9f,
                            TotalBets = 20000,
                            TotalWins = 10000
                        },
                        new
                        {
                            Id = new Guid("08900a1f-1343-42ab-8da4-83aa649a363f"),
                            AverageBetAmount = 10f,
                            Category = "Card Game",
                            GameName = "Crazy 4 Poker",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9883),
                            PopularityScore = 7.8f,
                            TotalBets = 5000,
                            TotalWins = 2500
                        },
                        new
                        {
                            Id = new Guid("6bf857bc-6918-46cb-92eb-5657fffeb3f8"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "War",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9895),
                            PopularityScore = 6.3f,
                            TotalBets = 4000,
                            TotalWins = 2000
                        },
                        new
                        {
                            Id = new Guid("641b4bcb-75d5-459b-acb1-b3348077ae50"),
                            AverageBetAmount = 5f,
                            Category = "Recreational Machine",
                            GameName = "Big Six Wheel",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9905),
                            PopularityScore = 8.1f,
                            TotalBets = 8000,
                            TotalWins = 4000
                        },
                        new
                        {
                            Id = new Guid("0e802480-9bb6-436e-875b-1aa2b9e91403"),
                            AverageBetAmount = 12f,
                            Category = "Card Game",
                            GameName = "Caribbean Stud Poker",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9915),
                            PopularityScore = 7.4f,
                            TotalBets = 9000,
                            TotalWins = 4500
                        },
                        new
                        {
                            Id = new Guid("43fcdb06-8bc8-4b6c-9da4-8e0d54418c37"),
                            AverageBetAmount = 0.5f,
                            Category = "Recreational Machine",
                            GameName = "Penny Slots",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9925),
                            PopularityScore = 9.6f,
                            TotalBets = 25000,
                            TotalWins = 12500
                        },
                        new
                        {
                            Id = new Guid("7f2644ce-35d6-4e56-b29d-c2003e0c39f1"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Cribbage",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9935),
                            PopularityScore = 4.9f,
                            TotalBets = 2000,
                            TotalWins = 1000
                        },
                        new
                        {
                            Id = new Guid("5110ed46-edb3-46ae-b380-f242c8f36346"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Video Poker",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9946),
                            PopularityScore = 9.3f,
                            TotalBets = 15000,
                            TotalWins = 7500
                        },
                        new
                        {
                            Id = new Guid("b9312149-64f1-45a1-a269-74302fd7d2da"),
                            AverageBetAmount = 10f,
                            Category = "Card Game",
                            GameName = "Pontoon",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9956),
                            PopularityScore = 6.7f,
                            TotalBets = 6000,
                            TotalWins = 3000
                        },
                        new
                        {
                            Id = new Guid("8afaf069-d259-4492-b247-dbba77d8cb1c"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Fruit Machine",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9966),
                            PopularityScore = 8.5f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("e9a7905a-c687-43bc-bc08-29b39952c68e"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Gin Rummy",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9976),
                            PopularityScore = 5.2f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        },
                        new
                        {
                            Id = new Guid("fd606ffa-c422-426d-b99a-9dad0469929e"),
                            AverageBetAmount = 2f,
                            Category = "Recreational Machine",
                            GameName = "Video Slots",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9986),
                            PopularityScore = 9.7f,
                            TotalBets = 35000,
                            TotalWins = 17500
                        },
                        new
                        {
                            Id = new Guid("70014949-7ea3-4900-8f3a-bcfa503cfc8e"),
                            AverageBetAmount = 5f,
                            Category = "Board Game",
                            GameName = "Backgammon",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 906, DateTimeKind.Utc).AddTicks(9996),
                            PopularityScore = 7.3f,
                            TotalBets = 5000,
                            TotalWins = 2500
                        },
                        new
                        {
                            Id = new Guid("27cbb875-d953-42fe-827a-4240d305248a"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Keno Slot",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(29),
                            PopularityScore = 8.9f,
                            TotalBets = 12000,
                            TotalWins = 6000
                        },
                        new
                        {
                            Id = new Guid("f630c325-1104-41ac-91f6-639249ec55e6"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Hearts",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(39),
                            PopularityScore = 6.1f,
                            TotalBets = 4000,
                            TotalWins = 2000
                        },
                        new
                        {
                            Id = new Guid("0cb85667-c898-4ff8-817d-272c1a8599b8"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Video Keno",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(49),
                            PopularityScore = 9.1f,
                            TotalBets = 18000,
                            TotalWins = 9000
                        },
                        new
                        {
                            Id = new Guid("533da2dc-673a-4e01-8d3f-0354b8770d90"),
                            AverageBetAmount = 10f,
                            Category = "Card Game",
                            GameName = "Cassino",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(59),
                            PopularityScore = 6.4f,
                            TotalBets = 7000,
                            TotalWins = 3500
                        },
                        new
                        {
                            Id = new Guid("6cce60e8-6673-4c97-9ce6-f467484af37f"),
                            AverageBetAmount = 2f,
                            Category = "Recreational Machine",
                            GameName = "Slingo",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(69),
                            PopularityScore = 8.3f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("9f74e2b1-fcea-49e6-b20b-1ff07fc988ce"),
                            AverageBetAmount = 8f,
                            Category = "Card Game",
                            GameName = "Gin Poker",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(79),
                            PopularityScore = 5.7f,
                            TotalBets = 5000,
                            TotalWins = 2500
                        },
                        new
                        {
                            Id = new Guid("9ca63c63-826e-43bd-a7ed-46c0a74cac48"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Video Lottery Terminal",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(89),
                            PopularityScore = 9.4f,
                            TotalBets = 30000,
                            TotalWins = 15000
                        },
                        new
                        {
                            Id = new Guid("bcc89328-5d6c-408b-9948-fc21ba7ca12b"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Canasta",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(100),
                            PopularityScore = 4.8f,
                            TotalBets = 2000,
                            TotalWins = 1000
                        },
                        new
                        {
                            Id = new Guid("094bafb1-5d9d-4bb7-abdc-a3fe34299e6e"),
                            AverageBetAmount = 0.5f,
                            Category = "Recreational Machine",
                            GameName = "Penny Arcade Slots",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(109),
                            PopularityScore = 9.9f,
                            TotalBets = 35000,
                            TotalWins = 17500
                        },
                        new
                        {
                            Id = new Guid("4ed085f7-f5bf-4992-871f-cc92e335d483"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Crazy Eights",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(119),
                            PopularityScore = 5.4f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        },
                        new
                        {
                            Id = new Guid("6de60a03-6814-4d8b-b875-b9123757d60b"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Video Lottery",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(129),
                            PopularityScore = 9.7f,
                            TotalBets = 40000,
                            TotalWins = 20000
                        },
                        new
                        {
                            Id = new Guid("ff920073-08df-48d5-84ef-2e525f76c100"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Pinochle",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(139),
                            PopularityScore = 5.1f,
                            TotalBets = 2500,
                            TotalWins = 1250
                        },
                        new
                        {
                            Id = new Guid("9a93c0d6-077f-4d63-9b58-2a81828252ec"),
                            AverageBetAmount = 0.5f,
                            Category = "Recreational Machine",
                            GameName = "Penny Roulette",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(149),
                            PopularityScore = 8.6f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("bb790464-ae0b-44d5-827c-826347605ab2"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Euchre",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(159),
                            PopularityScore = 4.7f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        },
                        new
                        {
                            Id = new Guid("c303a47b-61f3-4bdc-9efe-e093f4c9975e"),
                            AverageBetAmount = 1f,
                            Category = "Recreational Machine",
                            GameName = "Video Blackjack",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(169),
                            PopularityScore = 9.5f,
                            TotalBets = 20000,
                            TotalWins = 10000
                        },
                        new
                        {
                            Id = new Guid("b6424ba6-5ba4-4b49-ba7e-75a53d18a4ca"),
                            AverageBetAmount = 5f,
                            Category = "Card Game",
                            GameName = "Spades",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(178),
                            PopularityScore = 6.2f,
                            TotalBets = 4000,
                            TotalWins = 2000
                        },
                        new
                        {
                            Id = new Guid("ccc484a9-5ed0-4ed4-9ac2-f77615566dd6"),
                            AverageBetAmount = 0.5f,
                            Category = "Recreational Machine",
                            GameName = "Penny Poker",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(188),
                            PopularityScore = 9.2f,
                            TotalBets = 15000,
                            TotalWins = 7500
                        },
                        new
                        {
                            Id = new Guid("48edddaf-0c9d-4a5f-bbd9-012ae12218b0"),
                            AverageBetAmount = 8f,
                            Category = "Card Game",
                            GameName = "Cribbage Poker",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(198),
                            PopularityScore = 6.6f,
                            TotalBets = 5000,
                            TotalWins = 2500
                        },
                        new
                        {
                            Id = new Guid("0279e3dd-386a-47f4-be2a-fa57afd55d9f"),
                            AverageBetAmount = 0.5f,
                            Category = "Recreational Machine",
                            GameName = "Penny Bingo",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(208),
                            PopularityScore = 8f,
                            TotalBets = 10000,
                            TotalWins = 5000
                        },
                        new
                        {
                            Id = new Guid("9a3fc456-17b8-4441-b772-c7580f77d227"),
                            AverageBetAmount = 8f,
                            Category = "Card Game",
                            GameName = "Gin Rummy Poker",
                            LastUpdated = new DateTime(2024, 1, 13, 13, 43, 16, 907, DateTimeKind.Utc).AddTicks(218),
                            PopularityScore = 5.6f,
                            TotalBets = 3000,
                            TotalWins = 1500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
